package chain

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/blindxfish/truthchain/wallet"
)

// TestBrowserWalletInterop verifies that keys, addresses and signatures produced
// by the browser wallet crypto (web/truthchain-wallet.js) are accepted by the
// node's Go verification code. The vectors are generated by:
//
//	node web/gen_vectors.js > chain/testdata/interop_vectors.json
//
// Committing the vectors lets this run in Go-only CI (no Node required).
func TestBrowserWalletInterop(t *testing.T) {
	data, err := os.ReadFile("testdata/interop_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}

	var v struct {
		Account struct {
			PrivateKeyHex string `json:"privateKeyHex"`
			Address       string `json:"address"`
		} `json:"account"`
		Recipient struct {
			Address string `json:"address"`
		} `json:"recipient"`
		Post     Post     `json:"post"`
		Transfer Transfer `json:"transfer"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("unmarshal vectors: %v", err)
	}

	// 1. Address derivation: the JS-derived address must match the Go wallet's.
	w, err := wallet.ImportFromPrivateKey(v.Account.PrivateKeyHex)
	if err != nil {
		t.Fatalf("import private key: %v", err)
	}
	if w.GetAddress() != v.Account.Address {
		t.Fatalf("address mismatch: Go derived %s, JS derived %s", w.GetAddress(), v.Account.Address)
	}

	// 2. Post: the browser-signed post must verify against its author.
	if err := v.Post.VerifySignature(); err != nil {
		t.Fatalf("browser-signed post failed node verification: %v", err)
	}
	if v.Post.Author != v.Account.Address {
		t.Fatalf("post author %s != account %s", v.Post.Author, v.Account.Address)
	}

	// 3. Transfer: the browser-signed transfer must fully validate on the node.
	ok, err := v.Transfer.VerifySignature()
	if err != nil || !ok {
		t.Fatalf("browser-signed transfer failed node verification: ok=%v err=%v", ok, err)
	}
	if err := v.Transfer.Validate(); err != nil {
		t.Fatalf("browser-signed transfer failed full validation: %v", err)
	}
	if v.Transfer.From != v.Account.Address || v.Transfer.To != v.Recipient.Address {
		t.Fatalf("transfer addresses mismatch")
	}
}
